version: '3.7'
services:

  anki_sync_server:
    image: ${DOCKER_IMAGE:-anki-sync-server}:${DOCKER_VERSION:-latest}
    container_name: anki_sync_server_${ANKISYNCD_PORT:-27701}
    ports:
      - ${ANKISYNCD_PORT:-27701}:${ANKISYNCD_PORT:-27701}
    environment:
      - ANKISYNCD_PORT=${ANKISYNCD_PORT:-27701}
      - ANKISYNCD_BASE_URL=${ANKISYNCD_BASE_URL:-/sync/}
      - ANKISYNCD_BASE_MEDIA_URL=${ANKISYNCD_BASE_MEDIA_URL:-/msync/}
      - ANKISYNCD_AUTH_DB_PATH=${ANKISYNCD_AUTH_DB_PATH:-./auth.db}
      - ANKISYNCD_SESSION_DB_PATH=${ANKISYNCD_SESSION_DB_PATH:-./session.db}
    volumes:
      - ${ANKISYNCD_DATA_ROOT:-../instances/anki_sync_server}:/srv/ankisyncd
    restart: always
    stdin_open: true
    tty: true

  